<?php 
require('fpdf/fpdf.php');
require_once ('jpgraph/src/jpgraph.php');
require_once ('jpgraph/src/jpgraph_pie.php');
require_once ('jpgraph/src/jpgraph_pie3d.php');

class PDF extends FPDF
{
	function Header()
	{
    $this->Image('../imagenes/logo_ibnorca.png',260,12,25,25,'PNG');
    $this->SetFont('Arial','B',10);
    $this->Cell(249,10,'Instituto Boliviano de Normalizacion y Calidad',1,0,'C');
	$this->Cell(30,30,'',1);
	$this->LN(10);
	$this->Cell(249,10,'REGISTRO',1,0,'C');
	$this->LN(10);
	$this->Cell(249,10,'INFORME TECNICO DE EVENTOS DE CAPACITACION',1,1,'C');
	}
	function Footer()
	{
	    $this->SetY(-15);
		$this->SetFont('Arial','B',9);
		$this->Cell(69,6,utf8_decode('IBNORCA © '),1,0,'C');
		$this->Cell(72,6,'CODIGO: REG-PRE-SEC-05-02.02',1,0,'C');
		$this->Cell(69,6,'V: 2015-09-17',1,0,'C');
	    $this->Cell(69,6,'Pagina '.$this->PageNo().' de {nb}',1,0,'R');
	}

}
$pdf = new PDF('L','mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFillColor(251,260,224);
//CABECERA DE INFORME (279)//
$altoGeneral=6;
$pdf->Ln(5);
$pdf->Cell(30,$altoGeneral,'EVENTO:',1,0,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(249,$altoGeneral,'{dato}',1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(30,$altoGeneral,'CODIGO:',1,0,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(109,$altoGeneral,'{dato}',1,0);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(30,$altoGeneral,'EXPOSITOR:',1,0,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(110,$altoGeneral,'{dato}',1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(30,$altoGeneral,'LUGAR:',1,0,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(109,$altoGeneral,'{dato}',1,0);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(30,$altoGeneral,'DURACION:',1,0,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(110,$altoGeneral,'{dato}',1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(30,$altoGeneral,'FECHA INICIO:',1,0,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(40,$altoGeneral,'{dato}',1,0);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(30,$altoGeneral,'FECHA FIN:',1,0,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(39,$altoGeneral,'{dato}',1,0);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(30,$altoGeneral,'HORARIO:',1,0,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(110,$altoGeneral,'{dato}',1,1);

//I. DATOS DEL CURSO//
$pdf->Ln(5);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(100,6,'I. DATOS DEL CURSO',0,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(70,$altoGeneral,'Nro. DE ALUMNOS PARTICIPANTES',1,0);
$pdf->SetFont('Arial','',9);
$pdf->Cell(69,$altoGeneral,'{dato}',1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(70,$altoGeneral,'TOTAL FACTURACION DEL CURSO',1,0);
$pdf->SetFont('Arial','',9);
$pdf->Cell(69,$altoGeneral,'{dato}',1,1);

//II. RESULTADO DE EVALUACION DE SATISFACCION DEL CLIENTE//
//1. Contenido y documentacion//
$altoCol=8.5;
$anchoCol_1=70;
$anchoCol_2=35;
$anchoCol_3=34;
$anchoCol_4=12;
$anchoCol_5=128;
$texto_1='Muy Satisfecho';
$texto_2='Satisfecho';
$texto_3='Normal';
$texto_4='Poco Satisfecho';
$texto_5='Nada Satisfecho';
$texto_6='TOTAL GENERAL';
$pdf->Ln(5);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(100,6,'II. RESULTADO DE EVALUACION DE SATISFACCION DEL CLIENTE',0,1);
$pdf->Ln(5);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(100,6,'1. CONTENIDO Y DOCUMENTACION',0,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,utf8_decode('Nivel de Satisfacción'),1,0,'L',true);
$pdf->Cell($anchoCol_2,$altoCol,'Cantidad',1,0,'C',true);
$pdf->Cell($anchoCol_3,$altoCol,'Porcentage',1,0,'C',true);
$pdf->Cell($anchoCol_4,$altoCol,'Color',1,0,'C',true);
$pdf->Cell($anchoCol_5,$altoCol,'Grafico',1,1,'C',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_1,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_1.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,0);
$posicionEnX=$pdf->GetX();
$posicionEnY=$pdf->GetY();
$pdf->Ln();
$pdf->Cell($anchoCol_1,$altoCol,$texto_2,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_2.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_3,1,0);
$pdf->Image('../imagenes/emoji_2.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_3.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_4,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_4.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_5,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_5.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_6,1,0);
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,'',1,1);
$pdf->SetY($posicionEnY);
$pdf->SetX($posicionEnX);
//PARA EL GRAFICO//
$data = array(50,40,30,20,10);// NOTA: Estos datos deben ser reemplazados por los obtenidos del sistema
$color=array('#28ff89','#00d5ff','#fff800','#dd00f4','#ff2932');
$graph = new PieGraph(520,350);
$theme_class= new VividTheme;
$graph->SetTheme($theme_class);
$p1 = new PiePlot3D($data);
$graph->Add($p1);
$p1->ShowBorder();
$p1->SetColor('black');
$p1->SetSize(220);
$p1->value->SetFont(FF_ARIAL,FS_NORMAL,13);
$p1->SetSliceColors($color);
$nombreImagen = 'imagen_1.png';
$graph->Stroke($nombreImagen);

$pdf->Cell($anchoCol_5,($altoCol*6),$pdf->Image('imagen_1.png',($pdf->getX()+25),$pdf->getY(),null,($altoCol*6)),1,1);

$pdf->AddPage();
//2. Evaluacion al expositor//
$pdf->Ln(2);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(100,6,'2. EVALUACION AL EXPOSITOR',0,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,utf8_decode('Nivel de Satisfacción'),1,0,'L',true);
$pdf->Cell($anchoCol_2,$altoCol,'Cantidad',1,0,'C',true);
$pdf->Cell($anchoCol_3,$altoCol,'Porcentage',1,0,'C',true);
$pdf->Cell($anchoCol_4,$altoCol,'Color',1,0,'C',true);
$pdf->Cell($anchoCol_5,$altoCol,'Grafico',1,1,'C',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_1,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_1.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,0);
$posicionEnX=$pdf->GetX();
$posicionEnY=$pdf->GetY();
$pdf->Ln();
$pdf->Cell($anchoCol_1,$altoCol,$texto_2,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_2.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_3,1,0);
$pdf->Image('../imagenes/emoji_2.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_3.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_4,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_4.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_5,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_5.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_6,1,0);
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,'',1,1);
$pdf->SetY($posicionEnY);
$pdf->SetX($posicionEnX);
//PARA EL GRAFICO//
$data = array(10,20,30,40,50);// NOTA: Estos datos deben ser reemplazados por los obtenidos del sistema
$color=array('#28ff89','#00d5ff','#fff800','#dd00f4','#ff2932');
$graph = new PieGraph(520,350);
$theme_class= new VividTheme;
$graph->SetTheme($theme_class);
$p1 = new PiePlot3D($data);
$graph->Add($p1);
$p1->ShowBorder();
$p1->SetColor('black');
$p1->SetSize(220);
$p1->value->SetFont(FF_ARIAL,FS_NORMAL,13);
$p1->SetSliceColors($color);
$nombreImagen = 'imagen_2.png';
$graph->Stroke($nombreImagen);

$pdf->Cell($anchoCol_5,($altoCol*6),$pdf->Image('imagen_2.png',($pdf->getX()+25),$pdf->getY(),null,($altoCol*6)),1,1);
$pdf->Ln(5);
//3. Organizacion y logistica//
$pdf->SetFont('Arial','B',9);
$pdf->Cell(100,6,'3. ORGANIZACION Y LOGISTICA',0,1);
$pdf->Cell(100,6,'A) Ambiente, equipos, material auidiovisual (a,b,d)',0,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,utf8_decode('Nivel de Satisfacción'),1,0,'L',true);
$pdf->Cell($anchoCol_2,$altoCol,'Cantidad',1,0,'C',true);
$pdf->Cell($anchoCol_3,$altoCol,'Porcentage',1,0,'C',true);
$pdf->Cell($anchoCol_4,$altoCol,'Color',1,0,'C',true);
$pdf->Cell($anchoCol_5,$altoCol,'Grafico',1,1,'C',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_1,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_1.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,0);
$posicionEnX=$pdf->GetX();
$posicionEnY=$pdf->GetY();
$pdf->Ln();
$pdf->Cell($anchoCol_1,$altoCol,$texto_2,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_2.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_3,1,0);
$pdf->Image('../imagenes/emoji_2.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_3.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_4,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_4.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_5,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_5.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_6,1,0);
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,'',1,1);
$pdf->SetY($posicionEnY);
$pdf->SetX($posicionEnX);
//PARA EL GRAFICO//
$data = array(50,40,30,20,10);// NOTA: Estos datos deben ser reemplazados por los obtenidos del sistema
$color=array('#28ff89','#00d5ff','#fff800','#dd00f4','#ff2932');
$graph = new PieGraph(520,350);
$theme_class= new VividTheme;
$graph->SetTheme($theme_class);
$p1 = new PiePlot3D($data);
$graph->Add($p1);
$p1->ShowBorder();
$p1->SetColor('black');
$p1->SetSize(220);
$p1->value->SetFont(FF_ARIAL,FS_NORMAL,13);
$p1->SetSliceColors($color);
$nombreImagen = 'imagen_3.png';
$graph->Stroke($nombreImagen);

$pdf->Cell($anchoCol_5,($altoCol*6),$pdf->Image('imagen_3.png',($pdf->getX()+25),$pdf->getY(),null,($altoCol*6)),1,1);
$pdf->AddPage();
//3. Organizacion y logistica//
$pdf->Ln(2);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(100,6,utf8_decode('B) Organización del curso (Horario, duración y atención al cliente (e, f, g))'),0,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,utf8_decode('Nivel de Satisfacción'),1,0,'L',true);
$pdf->Cell($anchoCol_2,$altoCol,'Cantidad',1,0,'C',true);
$pdf->Cell($anchoCol_3,$altoCol,'Porcentage',1,0,'C',true);
$pdf->Cell($anchoCol_4,$altoCol,'Color',1,0,'C',true);
$pdf->Cell($anchoCol_5,$altoCol,'Grafico',1,1,'C',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_1,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_1.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,0);
$posicionEnX=$pdf->GetX();
$posicionEnY=$pdf->GetY();
$pdf->Ln();
$pdf->Cell($anchoCol_1,$altoCol,$texto_2,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_2.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_3,1,0);
$pdf->Image('../imagenes/emoji_2.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_3.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_4,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_4.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_5,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_5.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_6,1,0);
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,'',1,1);
$pdf->SetY($posicionEnY);
$pdf->SetX($posicionEnX);
//PARA EL GRAFICO//
$data = array(50,40,30,20,10);// NOTA: Estos datos deben ser reemplazados por los obtenidos del sistema
$color=array('#28ff89','#00d5ff','#fff800','#dd00f4','#ff2932');
$graph = new PieGraph(520,350);
$theme_class= new VividTheme;
$graph->SetTheme($theme_class);
$p1 = new PiePlot3D($data);
$graph->Add($p1);
$p1->ShowBorder();
$p1->SetColor('black');
$p1->SetSize(220);
$p1->value->SetFont(FF_ARIAL,FS_NORMAL,13);
$p1->SetSliceColors($color);
$nombreImagen = 'imagen_4.png';
$graph->Stroke($nombreImagen);

$pdf->Cell($anchoCol_5,($altoCol*6),$pdf->Image('imagen_4.png',($pdf->getX()+25),$pdf->getY(),null,($altoCol*6)),1,1);
$pdf->Ln(5);
//4. Aspectos generales//
$pdf->SetFont('Arial','B',9);
$pdf->Cell(100,6,'4. ASPECTOS GENERALES',0,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(100,6,utf8_decode('A) Comprensión, aplicabilidad y cumplimiento de expectativas (a, b, c)'),0,1);
$pdf->Cell($anchoCol_1,$altoCol,utf8_decode('Nivel de Satisfacción'),1,0,'L',true);
$pdf->Cell($anchoCol_2,$altoCol,'Cantidad',1,0,'C',true);
$pdf->Cell($anchoCol_3,$altoCol,'Porcentage',1,0,'C',true);
$pdf->Cell($anchoCol_4,$altoCol,'Color',1,0,'C',true);
$pdf->Cell($anchoCol_5,$altoCol,'Grafico',1,1,'C',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_1,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_1.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,0);
$posicionEnX=$pdf->GetX();
$posicionEnY=$pdf->GetY();
$pdf->Ln();
$pdf->Cell($anchoCol_1,$altoCol,$texto_2,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_2.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_3,1,0);
$pdf->Image('../imagenes/emoji_2.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_3.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_4,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_4.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_5,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_5.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_6,1,0);
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,'',1,1);
$pdf->SetY($posicionEnY);
$pdf->SetX($posicionEnX);
//PARA EL GRAFICO//
$data = array(50,40,30,20,10);// NOTA: Estos datos deben ser reemplazados por los obtenidos del sistema
$color=array('#28ff89','#00d5ff','#fff800','#dd00f4','#ff2932');
$graph = new PieGraph(520,350);
$theme_class= new VividTheme;
$graph->SetTheme($theme_class);
$p1 = new PiePlot3D($data);
$graph->Add($p1);
$p1->ShowBorder();
$p1->SetColor('black');
$p1->SetSize(220);
$p1->value->SetFont(FF_ARIAL,FS_NORMAL,13);
$p1->SetSliceColors($color);
$nombreImagen = 'imagen_5.png';
$graph->Stroke($nombreImagen);

$pdf->Cell($anchoCol_5,($altoCol*6),$pdf->Image('imagen_5.png',($pdf->getX()+25),$pdf->getY(),null,($altoCol*6)),1,1);
$pdf->AddPage();
//4. Aspectos generales//
$pdf->Ln(2);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(100,6,utf8_decode('B) Grado de satisfacción general del curso (d, e)'),0,1);
$pdf->Cell($anchoCol_1,$altoCol,utf8_decode('Nivel de Satisfacción'),1,0,'L',true);
$pdf->Cell($anchoCol_2,$altoCol,'Cantidad',1,0,'C',true);
$pdf->Cell($anchoCol_3,$altoCol,'Porcentage',1,0,'C',true);
$pdf->Cell($anchoCol_4,$altoCol,'Color',1,0,'C',true);
$pdf->Cell($anchoCol_5,$altoCol,'Grafico',1,1,'C',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_1,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_1.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,0);
$posicionEnX=$pdf->GetX();
$posicionEnY=$pdf->GetY();
$pdf->Ln();
$pdf->Cell($anchoCol_1,$altoCol,$texto_2,1,0);
$pdf->Image('../imagenes/emoji_1.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_2.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_3,1,0);
$pdf->Image('../imagenes/emoji_2.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_3.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_4,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_4.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->Cell($anchoCol_1,$altoCol,$texto_5,1,0);
$pdf->Image('../imagenes/emoji_3.png',($pdf->GetX()-($altoCol+2)),($pdf->GetY()+1),null,($altoCol-2),'PNG');
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,$pdf->Image('../imagenes/color_5.png',$pdf->getX(),$pdf->getY(),$anchoCol_4,$altoCol),1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell($anchoCol_1,$altoCol,$texto_6,1,0);
$pdf->Cell($anchoCol_2,$altoCol,'',1,0);
$pdf->Cell($anchoCol_3,$altoCol,'',1,0);
$pdf->Cell($anchoCol_4,$altoCol,'',1,1);
$pdf->SetY($posicionEnY);
$pdf->SetX($posicionEnX);
//PARA EL GRAFICO//
$data = array(50,40,30,20,10);// NOTA: Estos datos deben ser reemplazados por los obtenidos del sistema
$color=array('#28ff89','#00d5ff','#fff800','#dd00f4','#ff2932');
$graph = new PieGraph(520,350);
$theme_class= new VividTheme;
$graph->SetTheme($theme_class);
$p1 = new PiePlot3D($data);
$graph->Add($p1);
$p1->ShowBorder();
$p1->SetColor('black');
$p1->SetSize(220);
$p1->value->SetFont(FF_ARIAL,FS_NORMAL,13);
$p1->SetSliceColors($color);
$nombreImagen = 'imagen_6.png';
$graph->Stroke($nombreImagen);

$pdf->Cell($anchoCol_5,($altoCol*6),$pdf->Image('imagen_6.png',($pdf->getX()+25),$pdf->getY(),null,($altoCol*6)),1,1);
$pdf->Ln(5);

$pdf->SetFont('Arial','B',9);
$pdf->Cell(279,8,'5. CURSOS SUGERIDOS',1,1,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(279,8,'',1,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(279,8,'6. SUGERENCIAS Y/O RECLAMOS',1,1,'L',true);
$pdf->SetFont('Arial','',9);
$pdf->Cell(279,8,'',1,1);
$pdf->Output();
//ELIMINAMOS IMAGENES//
unlink('imagen_1.png');
unlink('imagen_2.png');
unlink('imagen_3.png');
unlink('imagen_4.png');
unlink('imagen_5.png');
unlink('imagen_6.png');
?>